services:
  #PHP Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: cloudsigma.com/php
    container_name: backend
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: backend
      SERVICE_TAGS: dev
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/        # Mount source code
      - backend_vendor:/var/www/html/vendor  # Keep vendor folder
      - ./php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini # Custom PHP configuration
    networks:
      - app-network

  frontend:
    stdin_open: true
    container_name: frontend
    build:
      context: ../Frontend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ../Frontend:/var/www/html/
    networks:
      - app-network

  #Nginx Service
  webserver:
    depends_on:
      - backend
      - frontend
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "81:81"
    networks:
      - app-network
  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: learning_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
#Docker Networks
networks:
  app-network:
    driver: bridge

#Docker Volumes
volumes:
    backend_vendor:
    mysql_data:
